Assignment 2: Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/Date.cpp File Reference
Date.cpp File Reference
#include "Date.h"
#include <iostream>
#include <string>
Functions
istream & operator>> (istream &input, Date &D)
Input file operator.
ostream & operator<< (ostream &os, const Date &D)
Output file operator.
bool operator< (const Date &first, const Date &second)
Overload operator.
bool operator== (const Date &first, const Date &second)
Overload operator.
Function Documentation
operator<()
bool operator< (const Date & first, const Date & second)
Overload operator.
This operator is used to compare 2 Date class objects and return true if the first Date class object is smaller than the second Date class object.
Parameters
first - First Date class object
second - Second Date class object
Returns
bool
Definition at line 231 of file Date.cpp.
 {
     if(first.GetDateObj()==second.GetDateObj())
     {
         return false;
     }
     if(first.GetYear() > second.GetYear())
     {
         return false;
     }
     if(first.GetYear() == second.GetYear())
     {
         if(first.GetMonth() > second.GetMonth())
         {
             return false;
         }
     }
     if(first.GetYear() == second.GetYear() && first.GetMonth() == second.GetMonth())
     {
         if(first.GetDay() > second.GetDay())
         {
             return false;
         }
     }
     return true;
 }
References Date::GetDateObj(), Date::GetDay(), Date::GetMonth(), Date::GetYear(), and operator==().
operator<<()
ostream& operator<< (ostream & os, const Date & D)
Output file operator.
This operator will output some information into a output file.
Parameters
os - Name of output file
Returns
Date
Definition at line 223 of file Date.cpp.
 {
     os <<"Date: "<<D.GetDay()<< " " << D.GetMonthInString()<< " " << D.GetYear()<<'\n';
     return os;
 }
operator==()
bool operator== (const Date & first, const Date & second)
Overload operator.
This operator is used to compare 2 pass in Date class objects and check whether there are same.
Parameters
first - First Date class object
second - Second Date class object
Returns
bool
Definition at line 263 of file Date.cpp.
 {
     if(first.GetYear() == second.GetYear())
     {
         if(first.GetMonth()==second.GetMonth())
         {
             if(first.GetDay()==second.GetDay())
             {
                 return true;
             }
         }
     }
     return false;
 }
References Date::GetDay(), Date::GetMonth(), and Date::GetYear().
Referenced by operator<(), and operator>().
operator>>()
istream& operator>> (istream & input, Date & D)
Input file operator.
This operator will read some information from a output file.
Parameters
input - Name of input file
Returns
Date
Definition at line 203 of file Date.cpp.
 {
     int day, month, year;
     char slash;
     if(input.peek() != '\n')
     {
         input >> day >> slash >> month >> slash >> year;
     }
     else
     {
         input.ignore(1); //ignore '\n'
         input >> day >> slash >> month >> slash >> year;
     }
     D.SetDate(day, month, year);
     return input;
 }
References Date::SetDate().