Assignment 2: Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/Time.h File Reference
Time.h File Reference
#include <iostream>
Classes
class Time
Represent the Time of marks were obtained.
Functions
ostream & operator<< (ostream &os, const Time &T)
Output file operator.
istream & operator>> (istream &input, Time &T)
Input file operator.
bool operator< (const Time &first, const Time &second)
Overload operator.
bool operator== (const Time &first, const Time &second)
Overload operator.
Function Documentation
operator<()
bool operator< (const Time & first, const Time & second)
Overload operator.
This operator is used to compare 2 Time class objects and return true if the first Time class object is smaller than the second Time class object.
Parameters
first - First Time class object
second - Second Time class object
Returns
bool
Definition at line 93 of file Time.cpp.
 {
     if(first == second)
     {
         return false;
     }
     if(first.GetHour() < second.GetHour())
     {
         return true;
     }
     else if(first.GetHour() == second.GetHour())
     {
         if(first.GetMinute() < second.GetMinute())
         {
             return true;
         }
     }
     return false;
 }
References Time::GetHour(), Time::GetMinute(), and operator==().
operator<<()
ostream& operator<< (ostream & os, const Time & T)
Output file operator.
This operator will output some information into a output file.
Parameters
os - Name of output file
Returns
Time
Definition at line 65 of file Time.cpp.
 {
     os << T.GetHour() << ":" << T.GetMinute() << '\n';
     return os;
 }
operator==()
bool operator== (const Time & first, const Time & second)
Overload operator.
This operator is used to compare 2 pass in Time class objects and check whether there are same Time.
Parameters
first - First Time class object
second - Second Time class object
Returns
bool
Definition at line 115 of file Time.cpp.
 {
     if(first.GetHour()==second.GetHour() && first.GetMinute()==second.GetMinute())
     {
         return true;
     }
     return false;
 }
References Time::GetHour(), and Time::GetMinute().
Referenced by operator<().
operator>>()
istream& operator>> (istream & input, Time & T)
Input file operator.
This operator will read some information from a output file.
Parameters
input - Name of input file
Returns
Time
Definition at line 71 of file Time.cpp.
 {
     int hour, minute;
     char colon;
     if(input.peek() != '\n')
     {
         input >> hour >> colon >> minute;
     }
     else
     {
         input.ignore(1); //ignore '\n'
         input >> hour >> colon >> minute;
     }
     //set the Time object
     T.SetHour(hour);
     T.SetMinute(minute);
     return input;
 }
References Time::SetHour(), and Time::SetMinute().