Assignment 2: Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/WindLogInfo.h File Reference
WindLogInfo.h File Reference
#include <iostream>
Classes
class WindLogInfo
Represent some historical data recorded by sensors.
Functions
ostream & operator<< (ostream &os, const WindLogInfo &W)
Output file operator.
istream & operator>> (istream &input, WindLogInfo &W)
Input file operator.
Function Documentation
operator<<()
ostream& operator<< (ostream & os, const WindLogInfo & W)
Output file operator.
This operator will output some information into a output file.
Parameters
os - Name of output file
Returns
WindLogInfo
Definition at line 79 of file WindLogInfo.cpp.
 {
     os << "Speed: " << W.GetSpeed() << '\n'
        << "Solar radiation: " << W.GetSolar() <<'\n'
        << "Ambient air temperature: " << W.GetAir() << '\n';
     return os;
 }
operator>>()
istream& operator>> (istream & input, WindLogInfo & W)
Input file operator.
This operator will read some information from a output file.
Parameters
input - Name of input file
Returns
WindLogInfo
Definition at line 57 of file WindLogInfo.cpp.
 {
     float speed, solar, air;
     char comma;
     if(input.peek() != '\n')
     {
         input >> speed >> comma >> solar >> comma >> air;
     }
     else
     {
         input.ignore(1); //ignore '\n'
         input >> speed >> comma >> solar >> comma >> air;
     }
     W.SetSpeed(speed);
     W.SetSolar(solar);
     W.SetAir(air);
     return input;
 }
References WindLogInfo::SetAir(), WindLogInfo::SetSolar(), and WindLogInfo::SetSpeed().