Assignment 2: Time Class Reference
Time Class Reference
Represent the Time of marks were obtained.
#include <Time.h>
Public Member Functions
Time ()
Create Time object with default value.
Time (const int hour, const int minute)
Time class constructor with parameters.
void Clear ()
Set all the member variables of Time object to default value.
int GetHour () const
Get the hour of Time object.
void SetHour (int hour)
Set a new hour for Time class object.
int GetMinute () const
Get the minute of Time object.
void SetMinute (int minute)
Set a new minute for Time class object.
Private Attributes
int m_hour
int m_minute
Detailed Description
Represent the Time of marks were obtained.
Time class contains 2 different member variables, both m_hour and m_minute are all int type variable. This class also contains appropriate get/set functions and operator. The time in this class is 24 hours time. Inside the constructor and set functions also contains appropriate validation check to ensure the user enter valid time.
Author
Tee Yee Kang
Version
01
Date
25/10/2021 Tee Yee Kang, Started
Bug:
There is no bug in this program.
Definition at line 27 of file Time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
Create Time object with default value.
This is the default constructor. Inside the constructor will set the member variables to default value by using the Clear() method.
Definition at line 9 of file Time.cpp.
 {
     Clear();
 }
References Clear().
Time() [2/2]
Time::Time (const int hour, const int minute)
Time class constructor with parameters.
This is the constructor of Time class. Which will takes in 2 parameters. The constructor will then set the actual parameters to the member variables of Time class object.
Parameters
h - Hours
m - Minutes
Definition at line 14 of file Time.cpp.
 {
     if(hour>=0 && hour<=24 && minute>=0 && minute<=59)
     {
         m_hour = hour;
         m_minute = minute;
     }else
     {
         Clear();
         cout<<"Invalid time"<<endl;
     }
 }
References Clear(), m_hour, and m_minute.
Referenced by main().
Member Function Documentation
Clear()
void Time::Clear ()
Set all the member variables of Time object to default value.
This function is used to set default value for Time object.
Returns
void
Definition at line 27 of file Time.cpp.
 {
     m_hour = 0;
     m_minute = 00;
 }
References m_hour, and m_minute.
Referenced by Time().
GetHour()
int Time::GetHour () const
Get the hour of Time object.
This const function is used to return the time object's hour No input parameter is required.
Returns
int
Definition at line 33 of file Time.cpp.
 {
     return m_hour;
 }
References m_hour.
Referenced by operator<(), and operator==().
GetMinute()
int Time::GetMinute () const
Get the minute of Time object.
This const function is used to return the time object's minute No input parameter is required.
Returns
int
Definition at line 49 of file Time.cpp.
 {
     return m_minute;
 }
References m_minute.
Referenced by operator<(), and operator==().
SetHour()
void Time::SetHour (int hour)
Set a new hour for Time class object.
This function is used to set a new value for the hour of the Time class object.
Parameters
hour - New hour of Time object
Returns
void
Definition at line 38 of file Time.cpp.
 {
     if(hour>=0 && hour<=23)
     {
         m_hour = hour;
     }else
     {
         cout<<"There is invalid hour"<<endl;
     }
 }
References m_hour.
Referenced by main(), and operator>>().
SetMinute()
void Time::SetMinute (int minute)
Set a new minute for Time class object.
This function is used to set a new value for the minute of the Time class object.
Parameters
minute - New minute of Time object
Returns
void
Definition at line 54 of file Time.cpp.
 {
     if(minute>=0 && minute<=59)
     {
         m_minute = minute;
     }else
     {
         cout<<"There is invalid minute"<<endl;
     }
 }
References m_minute.
Referenced by main(), and operator>>().
Member Data Documentation
m_hour
int Time::m_hour private
Definition at line 102 of file Time.h.
Referenced by Clear(), GetHour(), SetHour(), and Time().
m_minute
int Time::m_minute private
Definition at line 103 of file Time.h.
Referenced by Clear(), GetMinute(), SetMinute(), and Time().
The documentation for this class was generated from the following files:
Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/Time.h
Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/Time.cpp