Assignment 2: Date Class Reference
Date Class Reference
Represent the date of marks were obtained.
#include <Date.h>
Public Member Functions
Date ()
Default Date class constructor.
Date (const int day, const int month, const int year)
Date class constructor with parameters.
void Clear ()
Set all the member variables of Date object to the default value.
void GetDate () const
Get the final output of Date object.
void SetDate (int day, int month, int year)
Set a new date for Date class object.
int GetDay () const
Get the day of the date when the marks were obtained.
void SetDay (int newDay)
Set a new day for Date class object.
int GetMonth () const
Get the month of the date when marks were obtained.
void SetMonth (int newMonth)
Set a new month for Date class object.
int GetYear () const
Get the year of the date when marks were obtained.
void SetYear (int newYear)
Set a new year for Date class object.
string GetMonthInString () const
Get the description of specific month.
bool ValidDate (int day, int month, int year)
Check for valid date.
bool IsLeapYear (int year)
Check for leap year.
Date GetDateObj () const
Get the Date object.
Private Attributes
int m_day
int m_month
int m_year
Detailed Description
Represent the date of marks were obtained.
Date class contains 3 different variables. m_day, m_month and m_year are all int type variable. This class also contains appropriate get/set functions and operator. Inside the constructor and set functions also contains appropriate validation check to ensure the user enter valid date.
Author
Tee Yee Kang
Version
01
Date
25/10/2021 Tee Yee Kang, Started
Bug:
There is no bug in this program.
Definition at line 27 of file Date.h.
Constructor & Destructor Documentation
Date() [1/2]
Date::Date ()
Default Date class constructor.
This is the default constructor. Inside the constructor will set the member variables to default value when creating an Unit object.
Definition at line 9 of file Date.cpp.
 {
     Clear();
 }
References Clear().
Date() [2/2]
Date::Date (const int day, const int month, const int year)
Date class constructor with parameters.
This is the constructor for Date class. Which will takes in 3 parameters. The constructor will then set the actual parameters to the member variables of Date class object.
Parameters
d - Day
m - Month
y - Year
Definition at line 14 of file Date.cpp.
 {
     if(ValidDate(day, month, year))
     {
         m_day = day;
         m_month = month;
         m_year = year;
     }
     else
     {
         Clear();
     }
 }
References Clear(), m_day, m_month, m_year, and ValidDate().
Referenced by DateTree(), GetDateObj(), and main().
Member Function Documentation
Clear()
void Date::Clear ()
Set all the member variables of Date object to the default value.
This function is used to clear/set default value for Date object.
Returns
void
Definition at line 28 of file Date.cpp.
 {
     m_day = 0;
     m_month = 0;
     m_year = 0;
 }
References m_day, m_month, and m_year.
Referenced by Date().
GetDate()
void Date::GetDate () const
Get the final output of Date object.
This constant function is used to return the date of the marks were obtained No input parameter is required and it is constant function. Therefore, no modification is allowed.
Returns
void
Definition at line 35 of file Date.cpp.
 {
     cout <<m_day << "/" << m_month << "/" << m_year << endl;
 }
Referenced by main().
GetDateObj()
Date Date::GetDateObj () const
Get the Date object.
This constant function is used to return the Date class object No input parameter is required.
Returns
Date
Definition at line 40 of file Date.cpp.
 {
     Date d(m_day, m_month, m_year);
     return d;
 }
References Date(), m_day, m_month, and m_year.
Referenced by operator<().
GetDay()
int Date::GetDay () const
Get the day of the date when the marks were obtained.
This constant function is used to return the day of the marks were obtained No input parameter is required.
Returns
int
Definition at line 89 of file Date.cpp.
 {
     return m_day;
 }
References m_day.
Referenced by operator<(), operator==(), and operator>().
GetMonth()
int Date::GetMonth () const
Get the month of the date when marks were obtained.
This constant function is used to return the month of the marks were obtained. No input parameter is required.
Returns
int
Definition at line 94 of file Date.cpp.
 {
     return m_month;
 }
References m_month.
Referenced by operator<(), operator==(), and operator>().
GetMonthInString()
string Date::GetMonthInString () const
Get the description of specific month.
This function is used to return the month in English word form.
Returns
string
Definition at line 104 of file Date.cpp.
 {
     string monthDesc;
     switch(m_month)
     {
     case 1:
         monthDesc = "January";
         break;
     case 2:
         monthDesc = "February";
         break;
     case 3:
         monthDesc = "March";
         break;
     case 4:
         monthDesc = "April";
         break;
     case 5:
         monthDesc = "May";
         break;
     case 6:
         monthDesc = "June";
         break;
     case 7:
         monthDesc = "July";
         break;
     case 8:
         monthDesc = "August";
         break;
     case 9:
         monthDesc = "September";
         break;
     case 10:
         monthDesc = "October";
         break;
     case 11:
         monthDesc = "November";
         break;
     case 12:
         monthDesc = "December";
         break;
     default:
         monthDesc = "Invalid date";
     }
     return monthDesc;
 }
References m_month.
GetYear()
int Date::GetYear () const
Get the year of the date when marks were obtained.
This constant function is used to return the year of the marks were obtained. No input parameter is required.
Returns
int
Definition at line 99 of file Date.cpp.
 {
     return m_year;
 }
References m_year.
Referenced by operator<(), operator==(), and operator>().
IsLeapYear()
bool Date::IsLeapYear (int year)
Check for leap year.
This boolean function is used to check is the year of Date class object is leap year or not.
Parameters
year - Year of date
Returns
bool
Definition at line 191 of file Date.cpp.
 {
     bool leapYear = false;
     if(((year % 4 == 0) && (year % 100 != 0)) || (year % 400 == 0))
     {
         leapYear = true;
     }
     return leapYear;
 }
Referenced by ValidDate().
SetDate()
void Date::SetDate (int day, int month, int year)
Set a new date for Date class object.
This function is used to set a new date for the Date class object. Takes in 3 int values to set the date of the Date class object.
Parameters
d - New day of date
m - New month of date
y - New year of date
Returns
void
Definition at line 46 of file Date.cpp.
 {
     if(ValidDate(day, month, year))
     {
         m_day = day;
         m_month = month;
         m_year = year;
     }
     else
     {
         cout<<"Invalid date "<<endl;
     }
 }
References m_day, m_month, m_year, and ValidDate().
Referenced by main(), and operator>>().
SetDay()
void Date::SetDay (int newDay)
Set a new day for Date class object.
This function is used to set a new day for the Date class object. Takes in an int value.
Parameters
newDay - New day of date
Returns
void
Definition at line 60 of file Date.cpp.
 {
     if(ValidDate(newDay, m_month, m_year))
     {
         m_day = newDay;
     }
     else
     {
         cout<<"Invalid day "<<endl;
     }
 }
References m_day, m_month, m_year, and ValidDate().
Referenced by main().
SetMonth()
void Date::SetMonth (int newMonth)
Set a new month for Date class object.
This overload function is used to set a new month for the Date class object. Only takes in a new month with int value.
Parameters
newMonth - New month of date
Returns
void
Definition at line 72 of file Date.cpp.
 {
     if(ValidDate(m_day, newMonth, m_year))
     {
         m_month = newMonth;
     }
     else
     {
         cout<<"Invalid month "<<endl;
     }
 }
References m_day, m_month, m_year, and ValidDate().
Referenced by main().
SetYear()
void Date::SetYear (int newYear)
Set a new year for Date class object.
This function is used to set a new year for the Date class object. Takes in an int value.
Parameters
newYear - New year of date
Returns
void
Definition at line 84 of file Date.cpp.
 {
     m_year = newYear;
 }
References m_year.
Referenced by main().
ValidDate()
bool Date::ValidDate (int day, int month, int year)
Check for valid date.
This boolean function is used to check if the date of Date class object is valid or not.
Parameters
day - day of date
month - month of date
year - Year of date
Returns
bool
Definition at line 152 of file Date.cpp.
 {
     bool valid = false;
     if(month==1 || month==3 || month==5 || month==7 || month==8 || month==10 ||month==12)
     {
         if(day >=0 && day<=31)
         {
             valid = true;
         }
     }
     else if(month==4 || month==6 || month==9 || month==11)
     {
         if(day >=0 && day<=30)
         {
             valid = true;
         }
     }
     else if(month==2)
     {
         if(IsLeapYear(year))
         {
             if(day >=0 && day<=29)
             {
                 valid = true;
             }
         }else
         {
             if(day >=0 && day<=28)
             {
                 valid = true;
             }
         }
     }
     return valid;
 }
References IsLeapYear().
Referenced by Date(), SetDate(), SetDay(), and SetMonth().
Member Data Documentation
m_day
int Date::m_day private
Definition at line 190 of file Date.h.
Referenced by Clear(), Date(), GetDateObj(), GetDay(), SetDate(), SetDay(), and SetMonth().
m_month
int Date::m_month private
Definition at line 191 of file Date.h.
Referenced by Clear(), Date(), GetDateObj(), GetMonth(), GetMonthInString(), SetDate(), SetDay(), and SetMonth().
m_year
int Date::m_year private
Definition at line 192 of file Date.h.
Referenced by Clear(), Date(), GetDateObj(), GetYear(), SetDate(), SetDay(), SetMonth(), and SetYear().
The documentation for this class was generated from the following files:
Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/Date.h
Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/Date.cpp