Assignment 2: WindLogInfo Class Reference
WindLogInfo Class Reference
Represent some historical data recorded by sensors.
#include <WindLogInfo.h>
Public Member Functions
WindLogInfo ()
Default WindLogInfo class constructor.
WindLogInfo (const float speed, const float solar, const float air)
WindLogInfo class constructor with parameters.
void Clear ()
Set all the member variables of WindLogInfo object to the default value.
float GetSpeed () const
Get the speed of WindLogInfo object.
void SetSpeed (float newSpeed)
Set a new speed for WindLogInfo class object.
float GetSolar () const
Get the solar radiation of WindLogInfo object.
void SetSolar (float newSolar)
Set a new solar radiation for WindLogInfo class object.
float GetAir () const
Get the ambient air temperature of WindLogInfo object.
void SetAir (float newAir)
Set a new ambient air temperature for WindLogInfo class object.
Private Attributes
float m_speed
float m_solar
float m_air
Detailed Description
Represent some historical data recorded by sensors.
Date class contains 3 different variables, m_speed, m_solar and m_air are all float type variable. This class also contains appropriate get/set functions and operator.
Author
Tee Yee Kang
Version
01
Date
25/10/2021 Tee Yee Kang, Started
Bug:
There is no bug in this program.
Definition at line 24 of file WindLogInfo.h.
Constructor & Destructor Documentation
WindLogInfo() [1/2]
WindLogInfo::WindLogInfo ()
Default WindLogInfo class constructor.
This is the default constructor. Inside the constructor will set the member variables to default value when creating an WindLogInfo object.
Definition at line 8 of file WindLogInfo.cpp.
 {
     Clear();
 }
References Clear().
WindLogInfo() [2/2]
WindLogInfo::WindLogInfo (const float speed, const float solar, const float air)
WindLogInfo class constructor with parameters.
This is the constructor for WindLogInfo class. Which will takes in 3 parameters. The constructor will then set the actual parameters to the member variables of Date class object.
Parameters
speed - Speed
solar - Solar radiation
air - Ambient air temperature
Definition at line 13 of file WindLogInfo.cpp.
 {
     m_speed = speed;
     m_solar = solar;
     m_air = air;
 }
References m_air, m_solar, and m_speed.
Member Function Documentation
Clear()
void WindLogInfo::Clear ()
Set all the member variables of WindLogInfo object to the default value.
This function is used to clear/set default value for WindLogInfo object.
Returns
void
Definition at line 20 of file WindLogInfo.cpp.
 {
     m_speed = 0;
     m_solar = 0;
     m_air = 0;
 }
References m_air, m_solar, and m_speed.
Referenced by WindLogInfo().
GetAir()
float WindLogInfo::GetAir () const
Get the ambient air temperature of WindLogInfo object.
This constant function is used to return the ambient air temperature of the WindLogInfo object. No input parameter is required.
Returns
float
Definition at line 47 of file WindLogInfo.cpp.
 {
     return m_air;
 }
References m_air.
GetSolar()
float WindLogInfo::GetSolar () const
Get the solar radiation of WindLogInfo object.
This constant function is used to return the value solar radiation of the WindLogInfo object. No input parameter is required.
Returns
float
Definition at line 37 of file WindLogInfo.cpp.
 {
     return m_solar;
 }
References m_solar.
GetSpeed()
float WindLogInfo::GetSpeed () const
Get the speed of WindLogInfo object.
This constant function is used to return the recorded speed of WindLogInfo object No input parameter is required and it is constant function. Therefore, modification is not allowed.
Returns
float
Definition at line 27 of file WindLogInfo.cpp.
 {
     return m_speed;
 }
References m_speed.
SetAir()
void WindLogInfo::SetAir (float newAir)
Set a new ambient air temperature for WindLogInfo class object.
This function is used to set a new value of ambient air temperature for the WindLogInfo class object.
Parameters
newAir - New value of ambient air temperature
Returns
void
Definition at line 52 of file WindLogInfo.cpp.
 {
     m_air = newAir;
 }
References m_air.
Referenced by main(), and operator>>().
SetSolar()
void WindLogInfo::SetSolar (float newSolar)
Set a new solar radiation for WindLogInfo class object.
This function is used to set a new value of solar radiation for the WindLogInfo class object.
Parameters
newSolar - New value of solar radiation
Returns
void
Definition at line 42 of file WindLogInfo.cpp.
 {
     m_solar = newSolar;
 }
References m_solar.
Referenced by main(), and operator>>().
SetSpeed()
void WindLogInfo::SetSpeed (float newSpeed)
Set a new speed for WindLogInfo class object.
This function is used to set a new speed value for the WindLogInfo class object.
Parameters
newSpeed - New value of speed
Returns
void
Definition at line 32 of file WindLogInfo.cpp.
 {
     m_speed = newSpeed;
 }
References m_speed.
Referenced by main(), and operator>>().
Member Data Documentation
m_air
float WindLogInfo::m_air private
Definition at line 123 of file WindLogInfo.h.
Referenced by Clear(), GetAir(), SetAir(), and WindLogInfo().
m_solar
float WindLogInfo::m_solar private
Definition at line 122 of file WindLogInfo.h.
Referenced by Clear(), GetSolar(), SetSolar(), and WindLogInfo().
m_speed
float WindLogInfo::m_speed private
Definition at line 121 of file WindLogInfo.h.
Referenced by Clear(), GetSpeed(), SetSpeed(), and WindLogInfo().
The documentation for this class was generated from the following files:
Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/WindLogInfo.h
Practical_Work/ICT283_Assignment2_Tee_Yee_Kang_34315323/WindLogInfo.cpp